export default {
  CHAT_MESSAGE: 'CHAT_MESSAGE',
  CHAT_MESSAGE_REQUEST: 'CHAT_MESSAGE_REQUEST',
  CHAT_MESSAGE_PAGEREQUEST: 'CHAT_MESSAGE_PAGEREQUEST',
  CHAT_MESSAGE_SUCCESS: 'CHAT_MESSAGE_SUCCESS',
  CHAT_MESSAGE_FAILURE: 'CHAT_MESSAGE_FAILURE',
  CHAT_SEND: 'CHAT_SEND',
  CHAT_SEND_REQUEST: 'CHAT_SEND_REQUEST',
  CHAT_SEND_SUCCESS: 'CHAT_SEND_SUCCESS',
  CHAT_SEND_FAILURE: 'CHAT_SEND_FAILURE',
  CHAT_LATEST_MESSAGE: 'CHAT_LATEST_MESSAGE',
}